# Generated by Django 3.2.1 on 2021-06-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bronze'), (2, 'silver'), (3, 'gold')], default=1),
        ),
    ]
