# Generated by Django 3.2.1 on 2021-06-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classes_user'),
        ('profiles', '0002_alter_userprofile_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes'),
        ),
    ]
