# Generated by Django 3.2.1 on 2021-06-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classes_user'),
        ('profiles', '0003_userprofile_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.classes'),
        ),
    ]
