# Generated by Django 3.2.1 on 2021-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_time',
            field=models.CharField(max_length=15),
        ),
    ]
