# Generated by Django 3.2.1 on 2021-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210627_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='user',
        ),
    ]
